qemudriver: Handle Virtio GL change in 6.1.0
labgrid-project/labgrid pull request #1197
Opened 2023-06-06 13:15 UTC by JoshuaWatt

Starting with version 6.1.0, the QEMU command line argument to enable virtio with VirGL support was changed from "-vga virtio" to "-device virtio-vgal-gl". To correctly handle this, scrape the QEMU version number from the command output and use it to pass the correct arguments.

**Description**

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [x] PR has been tested

- [ ] Man pages have been regenerated

2023-06-07 11:10 UTC, jluebbe requested changes
Looks good otherwise.

2023-06-07 11:10 UTC, jluebbe commented on labgrid/driver/qemudriver.py
> +            raise ExecutionError(f"QEMU exited with: {p.returncode}")
This should mention that we tried to get the version.

2023-06-07 11:10 UTC, jluebbe commented on labgrid/driver/qemudriver.py
> +        p = subprocess.run([qemu_bin, "-version"], stdout=subprocess.PIPE, encoding="utf-8")
Perhaps move this into a helper function?

2023-06-13 06:28 UTC, Emantor approved these changes

2023-06-16 11:56 UTC, jluebbe approved these changes

2023-06-16 11:56 UTC, merged