sshdriver: Add Port Forwarding to Unix Sockets
labgrid-project/labgrid pull request #1262
Opened 2023-09-01 18:18 UTC by zmalinow

This commit adds a function that will forward a port on the local host to a unix socket on the target.

**Description**
Adds a function to the ssh driver that allows a unix socket on the target device to be forwarded to a tcp port on the host. This will allow tests to be performed against a running program that has no exposed ports.

**Checklist**
- [x] Documentation for the feature
- [x] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [x] PR has been tested

- [ ] Man pages have been regenerated

2023-09-06 10:00 UTC, Emantor submitted a review, later dismissed

2023-09-17 13:18 UTC, Bastian-Krause requested changes
Looks good otherwise.

2023-09-17 13:18 UTC, Bastian-Krause commented on tests/test_sshdriver.py
> +    localport = get_free_port()
This gets overwritten below.

2023-09-17 14:11 UTC, zmalinow commented on tests/test_sshdriver.py
> +    localport = get_free_port()
Done. I removed the superfluous line.

2023-09-17 16:52 UTC, Bastian-Krause approved these changes

2023-09-18 06:11 UTC, Emantor approved these changes

2023-09-18 06:11 UTC, merged