Fix modbus error parsing
labgrid-project/labgrid pull request #1311
Opened 2023-12-18 14:34 UTC by ep1cman

Small pr to fix an issue with handling error with modbus.

As per the documentation: https://pymodbustcp.readthedocs.io/en/latest/package/class_ModbusClient.html#pyModbusTCP.client.ModbusClient.last_error

`last_error` is a property, not a function

2023-12-18 21:26 UTC, Bastian-Krause approved these changes

2023-12-18 21:30 UTC, Bastian-Krause requested changes
Please prefix your commit title (`driver/modbusdriver: `), add the message from the PR to the commit message and add your SoB.

2023-12-19 00:01 UTC, ep1cman commented
Requested changes made

2023-12-19 09:23 UTC, Bastian-Krause approved these changes

2023-12-19 09:42 UTC, Bastian-Krause approved these changes
`last_error` was actually a method in pyModbusTCP 0.1.10, see [docs](https://pymodbustcp.readthedocs.io/en/v0.1.10/package/class_ModbusClient.html#pyModbusTCP.client.ModbusClient.last_error). I have added a commit to bump the minimum version of pyModbusTCP to >=0.2.0.

2023-12-19 11:16 UTC, ep1cman commented
Thanks for pointing out the change in the library. Upon further investigation I found another line that needed changing

2023-12-19 11:41 UTC, Bastian-Krause approved these changes

2023-12-21 09:46 UTC, merged