setuptools_scm: support reading version from archive
labgrid-project/labgrid pull request #1557
Opened 2024-12-10 08:41 UTC by alextercete

**Description**
Currently, it's not possible to `pip install` the `labgrid` package by using the GitHub archive URL. However, `setuptools_scm` [supports](https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives) this with a few files added to the repo.

**Testing**
This fails:
```
pip install https://github.com/labgrid-project/labgrid/zipball/master
```
This succeeds:
```
pip install https://github.com/arm-software/labgrid/zipball/pip-install-from-archive
```

**Checklist**
- [ ] Documentation for the feature: N/A
- [ ] Tests for the feature: N/A
- [x] PR has been tested

2025-01-06 06:14 UTC, Emantor requested changes

2025-01-06 06:14 UTC, Emantor commented on .git_archival.txt
> +describe-name: $Format:%(describe:tags=true,match=*[0-9]*)$
We should probably adjust this match to something like `v[0-9]+.[0-9]+.[0-9]+`?

2025-01-07 09:26 UTC, alextercete commented on .git_archival.txt
> +describe-name: $Format:%(describe:tags=true,match=*[0-9]*)$
Sure, it makes sense to be more specific. Although it looks like not all [tags](https://github.com/labgrid-project/labgrid/tags) follow that pattern. For example, major releases omit the patch number (e.g. `v24.0`). But I think `v[0-9]+.[0-9]+` should do the trick.

2025-01-07 09:51 UTC, alextercete commented on .git_archival.txt
> +describe-name: $Format:%(describe:tags=true,match=*[0-9]*)$
It turns out `match` takes a [`glob(7)`](https://www.man7.org/linux/man-pages/man7/glob.7.html) pattern, not a regular expression. So I think it would be best to go for `v[0-9]*` for simplicity.

2025-01-28 14:37 UTC, alextercete commented
@Emantor I've made the changes, would you mind taking another look?

2025-04-08 15:23 UTC, alextercete commented
@Emantor Just wanted to follow-up on this. Do you need me to do anything else here?

2025-04-08 19:17 UTC, Emantor approved these changes

2025-04-09 06:53 UTC, merged

2025-04-09 06:55 UTC, jluebbe commented
@alextercete Just out of interest, why would one use the tar archive instead of a git hash/branch?

2025-04-09 07:59 UTC, alextercete commented
@jluebbe The hash/branch URL requires `git` to be installed, whereas the archive URL works with just `pip`. This is particularly relevant when using something like Bazel, where [hermeticity](https://bazel.build/basics/hermeticity) is important.