labgrid: add uuuloader and uuudriver
labgrid-project/labgrid pull request #637
Opened 2020-09-16 13:37 UTC by jremmet

add driver for NXP mfgtools uuu
https://github.com/NXPmicro/mfgtools.git

Need to run uuu in a subprocess on its one. It takes some seconds to
return after sending the image to the target. Bootloader then runs
already and connecting to it is hard.

Signed-off-by: Jan Remmet <j.remmet@phytec.de>

**Description**

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] CHANGES.rst has been updated

- [ ] PR has been tested

- [ ] Man pages have been regenerated

2020-09-25 05:00 UTC, Emantor requested changes

2020-09-25 09:21 UTC, jremmet commented on labgrid/resource/udev.py
> +class UUULoader(USBResource):
I'll remove it and use IMXUSBLoader and MXSUSBLoader

2020-09-25 10:32 UTC, jremmet commented on labgrid/driver/usbloader.py
> +        # catch the starting bootloader.
Nice this works :)

2020-09-25 10:40 UTC, Emantor commented on labgrid/driver/usbloader.py
> +        # catch the starting bootloader.
Can we remove the subprocess with this? :)

2020-09-25 10:46 UTC, jremmet commented on labgrid/driver/usbloader.py
> +        # catch the starting bootloader.
Yes I'm working on this, thanks for the hint

2020-10-21 15:36 UTC, Emantor approved these changes

2020-10-26 11:47 UTC, merged