Update pytest and pytest-* to current versions
labgrid-project/labgrid pull request #642
Opened 2020-10-09 13:47 UTC by bgermann

Pytest 6 was released recently with a lot of imporvements and bug fixes.
Use the latest pytest version and the latest pytest plugin versions which
might have changes to be compatible with the 6.x versions.

**Description**

**Checklist**

- [x] PR has been tested

2020-10-09 14:33 UTC, Emantor commented
From the coverage diff it looks like the `junitxml` usage we currently use is no longer valid. This should be fixed before moving to pytest 6.x, since this outputs a jenkins compatible XML.

2020-10-21 14:33 UTC, bgermann commented
I think this should be fixed.

2020-10-21 15:23 UTC, Emantor requested changes
This looks good, thank you!
With the removal mentioned in the comments and a bump of the minimal pytest version in `setup.py` this should be good to go.

2020-10-21 15:23 UTC, Emantor commented on labgrid/pytestplugin/fixtures.py
>      if request.config.pluginmanager.hasplugin('junitxml'):
According to the source code at [pytest](https://docs.pytest.org/en/stable/_modules/_pytest/junitxml.html#record_testsuite_property), this should no longer be necessary, the fixture will return a no-op function in this case.

2020-10-21 15:35 UTC, Emantor approved these changes

2020-10-22 06:55 UTC, merged