client: Add LG_CLAIM_HOSTNAME/LG_CLAIM_USER
labgrid-project/labgrid pull request #690
Opened 2020-12-07 18:52 UTC by JPEWdev

Adds environment variables LG_CLAIM_HOSTNAME/LG_CLAIM_USER to control
the hostname and user that used to make a claim on a place. This is
useful in container based build pipelines where multiple pipeline stages
may need to use a claim, but the hostname and user name running in each
container differs (e.g. Tekton in Kubernetes).

Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>

**Description**

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] CHANGES.rst has been updated

- [ ] PR has been tested

- [ ] Man pages have been regenerated

2020-12-07 19:03 UTC, Emantor commented
My guess is that this is used to make the locking semantics static across multiple containers & users, i.e. your pipeline will always lock the place with something like `tekton/labgrid-test`.

2020-12-07 19:21 UTC, JPEWdev commented
> My guess is that this is used to make the locking semantics static across multiple containers & users, i.e. your pipeline will always lock the place with something like `tekton/labgrid-test`.

Correct. Specifically, I capture the (unique) name of the container/pipeline used to make the reservation, and the use that name in all subsequent containers. This makes it easy to trace a reservation back to a specific pipeline in the event something goes wrong and it gets left dangling (which is pretty rare because I have a finalize task that releases any reservations when the pipeline exits).

2020-12-07 20:13 UTC, Emantor approved these changes

2020-12-07 21:06 UTC, jluebbe commented
Is there a specific reason why you called it "claim"? That's not a term we've used in labgrid so far. Why not just "LG_HOSTNAME" and "LG_USERNAME"?

2020-12-07 21:10 UTC, JPEWdev commented
> Is there a specific reason why you called it "claim"? That's not a term we've used in labgrid so far. Why not just "LG_HOSTNAME" and "LG_USERNAME"?

It made sense to me.... but I don't really care. If you want it changed, let me know.

2020-12-08 13:10 UTC, Emantor requested changes
This needs to be added to the `labgrid-client` man page. I also prefer the either `LG_USER/HOSTNAME` or `LG_ACQUIRE_USER/HOSTNAME`, since we use `acquire` & `release` as the new naming semantics.

2020-12-08 13:17 UTC, jluebbe commented
Please just use LG_USERNAME/LG_HOSTNAME. :) They are also used for reservations, and we also have the lock alias for acquire.

2021-01-22 09:58 UTC, Emantor approved these changes

2021-01-22 09:58 UTC, merged