Draft: Check of hostname/username
labgrid-project/labgrid pull request #825
Opened 2021-09-03 12:52 UTC by MatthiasWeidmann

**Description**
Add a validation for hostname and username to not contain `/`.
Add also unit tests for checking the valid and invalid username/hostname.

**Checklist**
- [ ] Documentation for the feature
- [x] Tests for the feature 
- [ ] CHANGES.rst has been updated
- [ ] PR has been tested
- [ ] Man pages have been regenerated

Fixes #824

2021-11-04 13:48 UTC, jluebbe requested changes
The general approach looks fine.

I'd move the additional test cases to test_crossbar and just use simpler call than `reserve`/`reservations` (maybe just `show`).

Also, you need to add your Signed-off-by (https://labgrid.readthedocs.io/en/latest/development.html#developer-s-certificate-of-origin).

2021-11-04 13:48 UTC, jluebbe commented on tests/test_remote_client.py
> +        assert spawn.exitstatus == 0, spawn.before.strip()
This seems duplicated from `test_crossbar.py`. Please move them to `conftest.py` in a separate commit to allow them to be reused.

2021-11-04 13:48 UTC, jluebbe commented on tests/test_remote_client.py
> +    pass
Please remove this.

2021-11-04 13:48 UTC, jluebbe commented on tests/test_remote_client.py
> +def test_valid_hostname(place_acquire, tmpdir):
This should be called test_valid_**user**name.

2021-11-04 13:48 UTC, jluebbe commented on tests/test_remote_client.py
> +def test_invalid_hostname(place_acquire, tmpdir):
This should be called test_invalid_**user**name.

2026-01-30 17:35 UTC, Bastian-Krause commented
@MatthiasWeidmann Are you still interested in this?

2026-03-02 10:28 UTC, MatthiasWeidmann commented
Hi @Bastian-Krause 
the feature still sounds good to me. I moved on within the project I was working for.
Currently I do not have the time to check on updates and merge conflicts.
Feel free to pick up the changes or drop them.
Best regards

2026-08-07 14:09 UTC, Bastian-Krause commented
This never came up in the past 5 years, let's close this. If anyone likes to pick this up, we can still do that.

2026-08-07 14:09 UTC, closed without merging