remote/client: allow already locked resources
labgrid-project/labgrid pull request #832
Opened 2021-09-15 14:33 UTC by Emantor

**Description**

Allow a place to still be locked if one of the resources is acquired but
was previously acquired by the same place.

Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>

Not really sure how to test this.

**Checklist**
- [ ] CHANGES.rst has been updated
- [ ] PR has been tested

Fixes https://github.com/labgrid-project/labgrid/issues/748

2021-09-15 14:49 UTC, jluebbe commented
We can't just ignore the inconsistent state here. In the situation reported in #748, this would only allow using this resource by the same place, but if the resource is now configured to match for a different place, it cannot be acquired.
I suspect that the issue already exists before the failing acquire. @egrigore: Do you see any other tracebacks on the exporter or coordinator correlated to the issue?

2021-09-16 10:42 UTC, jluebbe requested changes
This should not be merged as is, see my comment above.

2021-09-16 10:45 UTC, Emantor commented
> This should not be merged as is, see my comment above.

I agree, closing.

2021-09-16 10:45 UTC, closed without merging

2022-01-12 15:45 UTC, egrigore commented
@jluebbe  sorry for the late response . We have seen this problem again today but there is nothing special related to it on exporter or coordinator journalctl . There aren't clear steps to isolate the problem and also it doesn't happen only on a specific board to relate it to that.