Add instructions to update pip when setting up a virtualenv for labgrid
labgrid-project/labgrid pull request #922
Opened 2022-05-23 15:03 UTC by NiklasReisser

**Description**

Extend Documentation to update pip when creating a new virtualenv. The dependency resolver of older pip versions (at least until 2.0.2, as shipped with Ubuntu 20.04) is not able to install the current set of required versions. 

Fixes #919

2022-05-23 16:11 UTC, Bastian-Krause commented
Thanks for your contribution!

Any reason why you use `python -m pip` instead of just `pip`?

2022-05-24 05:48 UTC, NiklasReisser commented
I literally copied the line you mentioned in the issue. :) 
It is also the way they do it in the python docs. Apart from choosing the interpreter when outside a virtualenv I don't know any reasons for it though.  

See: https://docs.python.org/3/installing/index.html

Technically an `pip install --upgrade pip` should be sufficient of course.

2022-05-25 06:09 UTC, NiklasReisser commented
Sure, I changed it

2022-05-25 10:13 UTC, Bastian-Krause requested changes
Looks good. One last improvement, though. If this is addressed, please squash your commits. Thanks!

2022-05-25 10:13 UTC, Bastian-Krause commented on doc/getting_started.rst
> +    $ pip install --upgrade pip setuptools wheel
```suggestion
    labgrid-venv $ pip install --upgrade pip setuptools wheel
```

2022-05-30 11:50 UTC, Bastian-Krause approved these changes
Thanks for your patience!

2022-05-30 12:30 UTC, merged

2022-05-30 12:31 UTC, Emantor commented
Thanks!