qemudriver: Add display support
labgrid-project/labgrid pull request #968
Opened 2022-08-17 21:36 UTC by JoshuaWatt

Adds support for configuring the driver to create a display device,
which can either be no device, a software framebuffer, or a accelerated
GPU (which requires host support)

**Description**

**Checklist**
- [x] Documentation for the feature
- [ ] Tests for the feature 

- [x] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [x] CHANGES.rst has been updated

- [x] PR has been tested

- [ ] Man pages have been regenerated

2022-08-18 15:15 UTC, jluebbe commented
Rebased to resolve conflict in `CHANGES.rst`.

2022-08-18 15:27 UTC, jluebbe submitted a review, later dismissed

2022-08-18 18:23 UTC, Bastian-Krause requested changes
Looks good to me, only a small suggestion regarding doc consistency.

2022-08-18 18:23 UTC, Bastian-Krause commented on doc/configuration.rst
> +  - display (str): optional, display output to enable; must be one of:
```suggestion
  - display (str, default="none"): optional, display output to enable; must be one of:
```
We mention always mention the default right after the parameter type.

2022-08-24 19:54 UTC, JoshuaWatt commented
Moved to #976

2022-08-24 19:54 UTC, closed without merging